{% set name = "scikit-posthocs" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scikit-posthocs-{{ version }}.tar.gz
  sha256: 272054f2f636c70933c9220e7057668e1912cbdcb67bf97db5aebb770fef8452

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - matplotlib-base
    - numpy
    - pandas >=0.20.0
    - python >=3.5
    - scipy
    - seaborn
    - statsmodels

test:
  imports:
    - scikit_posthocs
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/maximtrp/scikit-posthocs
  summary: Statistical post-hoc analysis and outlier detection algorithms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maximtrp
